package com.semicolon.mysoulmate;


import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import static com.codename1.ui.CN.getCurrentForm;
import com.codename1.ui.Toolbar;
import com.semicolon.gui.FeedbackView;
import com.semicolon.gui.InscriptionView;
import com.semicolon.gui.SignalView;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
//     FeedbackView m = new FeedbackView();
//     m.getF().show();
//        
//        SignalView v = new SignalView();
//        v.getF().show();
//        InscriptionView ins = new InscriptionView();
//        ins.getF().show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
